%
% subdivide_volume
%
% Given a center point, divide into eight subvolumes.
%
function [idx_000,idx_001,idx_010,idx_011,...
    idx_100,idx_101,idx_110,idx_111] = ...
...%function [idx_00,idx_01,idx_10,idx_11] = ...
    subdivide_volume(   Y1_, Y2_, Y3_, ...
                        min_x,min_y,min_z, ...
                        max_x,max_y,max_z, ...
                        m_width, m_height, m_depth )
                  
        idx_000 = find( ...
            Y1_ >= min_x & Y1_ < m_width &...
            Y2_ >= min_y & Y2_ < m_height &...
            Y3_ >= min_z & Y3_ < m_depth );
        idx_001 = find( ...
            Y1_ >= min_x & Y1_ < m_width &...
            Y2_ >= min_y & Y2_ < m_height &...
            Y3_ >= m_depth & Y3_ < max_z );
        idx_010 = find( ...
            Y1_ >= min_x & Y1_ < m_width &...
            Y2_ >= m_height & Y2_ < max_y &... 
            Y3_ >= min_z & Y3_ < m_depth );
        idx_011 = find( ...
            Y1_ >= min_x & Y1_ < m_width &...
            Y2_ >= m_height & Y2_ < max_y &...
            Y3_ >= m_depth  & Y3_ < max_z );

        idx_100 = find( ...
            Y1_ >= m_width & Y1_ < max_x &...
            Y2_ >= min_y & Y2_ < m_height &...
            Y3_ >= min_z & Y3_ < m_depth );
        
        idx_101 = find( ...
            Y1_ >= m_width & Y1_ < max_x &...
            Y2_ >= min_y & Y2_ < m_height &...
            Y3_ >= m_depth & Y3_ < max_z );
        
        idx_110 = find( ...
            Y1_ >= m_width & Y1_ < max_x &...
        	Y2_ >= m_height & Y2_ < max_y &...
            Y3_ >= min_z & Y3_ < m_depth );
        
        idx_111 = find( ...
            Y1_ >= m_width & Y1_ < max_x &...
        	Y2_ >= m_height & Y2_ < max_y &...            
            Y3_ >= m_depth & Y3_ < max_z );

end
        